<?php
class Menu
{
  static public function Monta($perfil)
  {
    $retorno = array();
    foreach ($perfil as $key => $value):
      $opt = $value["opt"];
      $ico = $value["ico"];
      $url = $value["url"];

      $urlEmpty = empty($url);
      $class = "";
      if ($value["active"]):
        $class = " class=\"" . ($urlEmpty ? "open" : "active") . "\"";
        if (!$urlEmpty):
          $retorno = array("opt" => $opt, "url" => $url);
        endif;
      endif;
      echo "<li$class>";
      if (!$urlEmpty):
        echo "<a href=\"" . CFG::Root() . "dashboard.php?id=$key\">";
      else:
        echo "<a href=\"#\" class=\"menu-dropdown\">";
      endif;
      if (!empty($ico)):
        echo "<i class=\"$ico\"></i>";
      endif;
      echo "<span class=\"menu-text\">$opt</span>";
      if (count($value["child"]) > 0):
        echo "<i class=\"menu-expand\"></i>";
      endif;
      echo "</a>";
      if (count($value["child"]) > 0):
        echo "<ul class=\"submenu\" style=\"display: none;\">";
        $ax = static::Monta($value["child"]);
        if (count($retorno) == 0):
          $retorno = $ax;
        endif;
        echo "</ul>";
      endif;
      echo "</li>";
    endforeach;
    return $retorno;
  }
  public static function List($profile, $event = null)
  {
    $onJoinEvent = " IS NULL";
    $binding = array($profile);
    if (!is_null($event)):
      $onJoinEvent = " = ?";
      $binding[] = $event;
    endif;

    return CONN::Get()->getAll("
    SELECT m.ID, m.CD, IF(f.DS IS NULL, m.DS, CONCAT(m.DS, ' [', f.DS, ']')) AS DS, m.ICON, f.ROUTE, pm.ID AS PID, pm.DH_INI_VALID, pm.DH_FIM_VALID
    FROM MENU m
    LEFT JOIN PROFILE_MENU pm ON (pm.MENU = m.ID AND pm.PROFILE = ? AND pm.EVENT$onJoinEvent)
    LEFT JOIN FUNCTIONALITY f ON (f.ID = m.FUNCTIONALITY)
    ORDER BY m.CD
    ", $binding);
  }

  public static function Profile($profile, $event = null)
  {
    return static::MakeOptions(static::list($profile, $event), true, null);
  }

  public static function MakeOptions($result, $allOptions = false, $fnFilter = null)
  {
    if (is_null($fnFilter)) $fnFilter = function ($k, $v) {
      return (strlen($k['CD']) == 2);
    };

    $arr = array();
    foreach (array_filter($result, $fnFilter, ARRAY_FILTER_USE_BOTH) as $key => $fields) :
      $children = static::MakeOptions($result, $allOptions, function ($k, $v) use ($fields) {
        return (str_starts_with($k['CD'], $fields['CD']) && strlen($k['CD']) == strlen($fields['CD']) + 3);
      });

      $checked = !empty($fields['ROUTE']) && !is_null($fields['PID']);
      if ($allOptions || !empty($fields['ROUTE']) || count($children) > 0) {
        $ds = Formatter::TitleCase($fields['DS']);
        if (!is_null(@$fields['SPLIT'])) $ds .= " - " . Formatter::TitleCase($fields['SPLIT']);

        $opt = array(
          "id" => $fields['ID'],
          "text" => $ds,
          "icon" => $fields['ICON'],
          "modal" => @$fields['MODAL'],
          "route" => $fields['ROUTE'],
          "pid" => $fields['PID'],
        );

        if ($allOptions):
          $opt["data"] = array(
            "fields" => array(
              array(
                'fl' => 'dhi',
                "vl" => Formatter::DateMask(Formatter::EmptyOr(@$fields['DH_INI_VALID'], ""), "d/m/Y H:i:s"),
              ),
              array(
                'fl' => 'dhf',
                "vl" => Formatter::DateMask(Formatter::EmptyOr(@$fields['DH_FIM_VALID'], ""), "d/m/Y H:i:s"),
              ),
            )
          );

          $opt["state"] = array(
            "partial" => !is_null($fields['PID']),
            "opened" => $checked,
            "disabled" => false,
            "selected" => $checked,
          );
        endif;

        if (count($children) > 0) $opt["children"] = $children;

        $arr[] = $opt;
      }
    endforeach;
    return $arr;

    //tree object
    // {
    //   id          : "string" // will be autogenerated if omitted
    //   text        : "string" // node text
    //   icon        : "string" // string for custom
    //   state       : {
    //     opened    : boolean  // is the node open
    //     disabled  : boolean  // is the node disabled
    //     selected  : boolean  // is the node selected
    //   },
    //   children    : []  // array of strings or objects
    //   li_attr     : {}  // attributes for the generated LI node
    //   a_attr      : {}  // attributes for the generated A node
    // }
  }
}
